### ISSUE TITLE
Unexpected KeyError

### ISSUE THREAD

**Issue by gjr80** [gjr80/weewx-aurora#9]
Seemed to be working but no uploads to PVOutput. Refer log extract

```
May 16 05:50:27 aurora weewx[645]: manager: Added record 2019-05-16 05:50:00 AEST (1557949800) to database 'aurora.sdb'
May 16 05:50:27 aurora weewx[645]: manager: Added record 2019-05-16 05:50:00 AEST (1557949800) to daily summary in 'aurora.sdb'
May 16 05:50:28 aurora weewx[645]: restx: PVOutput-API: Skipped record 2019-05-16 05:50:00 AEST (1557949800):
May 16 05:50:29 aurora weewx[645]: cheetahgenerator: Generated 6 files for report SeasonsAuroraReport in 1.10 seconds
May 16 05:50:29 aurora weewx[645]: imagegenerator: Generated 7 images for SeasonsAuroraReport in 0.52 seconds
May 16 05:50:29 aurora weewx[645]: copygenerator: copied 0 files to /home/weewx/public_html
May 16 05:50:30 aurora weewx[645]: rsyncupload: rsync'd 13 files (115,264 bytes) in 0.83 seconds
May 16 05:55:27 aurora weewx[645]: manager: Added record 2019-05-16 05:55:00 AEST (1557950100) to database 'aurora.sdb'
May 16 05:55:27 aurora weewx[645]: manager: Added record 2019-05-16 05:55:00 AEST (1557950100) to daily summary in 'aurora.sdb'
May 16 05:55:27 aurora weewx[645]: restx: PVOutput-API: Skipped record 2019-05-16 05:55:00 AEST (1557950100):
May 16 05:55:28 aurora weewx[645]: cheetahgenerator: Generated 6 files for report SeasonsAuroraReport in 1.11 seconds
May 16 05:55:29 aurora weewx[645]: imagegenerator: Generated 7 images for SeasonsAuroraReport in 0.52 seconds
May 16 05:55:29 aurora weewx[645]: copygenerator: copied 0 files to /home/weewx/public_html
May 16 05:55:30 aurora weewx[645]: rsyncupload: rsync'd 13 files (115,261 bytes) in 0.87 seconds
May 16 06:00:27 aurora weewx[645]: manager: Added record 2019-05-16 06:00:00 AEST (1557950400) to database 'aurora.sdb'
May 16 06:00:27 aurora weewx[645]: manager: Added record 2019-05-16 06:00:00 AEST (1557950400) to daily summary in 'aurora.sdb'
May 16 06:00:28 aurora weewx[645]: restx: PVOutput-API: Skipped record 2019-05-16 06:00:00 AEST (1557950400):
May 16 06:00:29 aurora weewx[645]: cheetahgenerator: Generated 6 files for report SeasonsAuroraReport in 1.12 seconds
May 16 06:00:32 aurora weewx[645]: imagegenerator: Generated 21 images for SeasonsAuroraReport in 2.68 seconds
May 16 06:00:32 aurora weewx[645]: copygenerator: copied 0 files to /home/weewx/public_html
May 16 06:00:33 aurora weewx[645]: rsyncupload: rsync'd 27 files (250,982 bytes) in 0.92 seconds
May 16 06:05:27 aurora weewx[645]: manager: Added record 2019-05-16 06:05:00 AEST (1557950700) to database 'aurora.sdb'
May 16 06:05:27 aurora weewx[645]: manager: Added record 2019-05-16 06:05:00 AEST (1557950700) to daily summary in 'aurora.sdb'
May 16 06:05:28 aurora weewx[645]: restx: PVOutput-API: Skipped record 2019-05-16 06:05:00 AEST (1557950700):
May 16 06:05:29 aurora weewx[645]: cheetahgenerator: Generated 6 files for report SeasonsAuroraReport in 1.14 seconds
May 16 06:05:29 aurora weewx[645]: imagegenerator: Generated 7 images for SeasonsAuroraReport in 0.60 seconds
May 16 06:05:29 aurora weewx[645]: copygenerator: copied 0 files to /home/weewx/public_html
May 16 06:05:30 aurora weewx[645]: rsyncupload: rsync'd 13 files (114,588 bytes) in 0.87 seconds
May 16 06:05:33 aurora weewx[645]: engine: Clock error is 7.32 seconds (positive is fast)
May 16 06:05:41 aurora weewx[645]: aurora: Inverter time was not set
May 16 06:05:41 aurora weewx[645]: engine: Main loop exiting. Shutting engine down.
May 16 06:05:41 aurora weewx[645]: engine: Shutting down StdReport thread
May 16 06:05:41 aurora weewx[645]: engine: Caught unrecoverable exception in engine:
May 16 06:05:41 aurora weewx[645]:     ****  None
May 16 06:05:41 aurora weewx[645]:     ****  Traceback (most recent call last):
May 16 06:05:41 aurora weewx[645]:     ****    File "/home/weewx/bin/weewx/engine.py", line 890, in main
May 16 06:05:41 aurora weewx[645]:     ****      engine.run()
May 16 06:05:41 aurora weewx[645]:     ****    File "/home/weewx/bin/weewx/engine.py", line 177, in run
May 16 06:05:41 aurora weewx[645]:     ****      self.dispatchEvent(weewx.Event(weewx.PRE_LOOP))
May 16 06:05:41 aurora weewx[645]:     ****    File "/home/weewx/bin/weewx/engine.py", line 224, in dispatchEvent
May 16 06:05:41 aurora weewx[645]:     ****      callback(event)
May 16 06:05:41 aurora weewx[645]:     ****    File "/home/weewx/bin/weewx/engine.py", line 681, in pre_loop
May 16 06:05:41 aurora weewx[645]:     ****      self.do_sync()
May 16 06:05:41 aurora weewx[645]:     ****    File "/home/weewx/bin/weewx/engine.py", line 701, in do_sync
May 16 06:05:41 aurora weewx[645]:     ****      self.engine.console.setTime()
May 16 06:05:41 aurora weewx[645]:     ****    File "/home/weewx/bin/user/aurora.py", line 774, in setTime
May 16 06:05:41 aurora weewx[645]:     ****      AuroraDriver.TRANSMISSION[_response.transmission_state]))
May 16 06:05:41 aurora weewx[645]:     ****  KeyError: None
May 16 06:05:41 aurora weewx[645]:     ****  Exiting.
```

**Comment by gjr80** [comment]
Error not seen again. Closing due to significant code base refactoring in v0.5.0
